### PR TITLE
Pull Request For Code Review

### PR DESCRIPTION
**Pull request by NiiazalyDzhumaliev**
Please kindly review my project.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
## Hi @NiiazalyDzhumaliev  ! Very very nice project! :wave: 

# Status: [changes required]

You have made great progress in this project. However, we need to fix it next before merging:

## [ OPTIONAL ] 
* [ ] Ruby methods automatically returns the last evaluated statement, therefore, there is no need for explicit declaration return

## [ GENERAL ]
 * [ ] Pull Request should have a meaningful title and a short description from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
screenshot 
* [ ] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)

screenshot 
### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by NiiazalyDzhumaliev** [comment]
I have implemented the enumerable methods as it was described in the Odin project. The method's tests were passed. I disable some rubocop as described in the Microverse description. The code became more complex because it should check for different objects.  Please kindly review my code.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
# Project Approved :thumbsup:
## Hello Team,  You have done a great job with this project. :clap:
All requirements have been met except one.
- The Pull Request should have a meaningful title 
#### You can go ahead and merge once you are done !!!
Note: You can edit the pull request title

**Review by kobiyoyo — APPROVED** [review]
Approved

**Pull request merged**
